name: Update impact metrics

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]             # 换成你的默认分支名
    paths:
      - 'scripts/fetch-metrics.mjs'
      - '.github/workflows/impact-metrics.yml'
      - 'package.json'
      - 'yarn.lock'
      - 'public/**'                # 可按需增减
  schedule:
    - cron: "*/5 * * * *"         # 每 5 分钟跑一次

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: Generate metrics JSON
        run: node scripts/fetch-metrics.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/impact_metrics.json || true
          git commit -m "chore: update impact metrics [skip ci]" || echo "No changes"
          git push
